const PUBLIC_API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;
const PUBLIC_URL = process.env.NEXT_PUBLIC_URL;
const THEME = process.env.NEXT_PUBLIC_THEME;
const PLUGIN_THEME = process.env.NEXT_PUBLIC_PLUGIN_THEME;
const FAVICON = process.env.NEXT_PUBLIC_FAVICON;
const GOOGLE_APP_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_APP_CLIENT_ID;

export { PUBLIC_URL, PUBLIC_API_ENDPOINT, THEME, PLUGIN_THEME, FAVICON, GOOGLE_APP_CLIENT_ID };
