const PUBLIC_API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;
const NEXT_PUBLIC_URL = process.env.NEXT_PUBLIC_NEXT_PUBLIC_URL;
const THEME = process.env.NEXT_PUBLIC_THEME;
const FAVICON = process.env.NEXT_PUBLIC_FAVICON;

export { NEXT_PUBLIC_URL, PUBLIC_API_ENDPOINT, THEME, FAVICON };
