export const swiperData = [
  {
    avatar: 'https://azureapis.blob.core.windows.net/share-account/assets/images/banner-1.jpg',
    title: 'Trending Item',
    info: "WOMEN'S LATEST FASHION SALE",
    price: 'starting at $ 20.00',
    button: 'SHOP NOW',
  },
  {
    avatar: 'https://azureapis.blob.core.windows.net/share-account/assets/images/banner-2.jpg',
    title: 'Trending Accessories',
    info: 'MODERN SUNGLASSES',
    price: 'starting at $ 15.00',
    button: 'SHOP NOW',
  },
  {
    avatar: 'https://azureapis.blob.core.windows.net/share-account/assets/images/banner-3.jpg',
    title: 'Sale Offer',
    info: 'NEW FASHION SUMMER SALE',
    price: 'starting at $ 29.99',
    button: 'SHOP NOW',
  },
];

export const TitleCategories = [
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/dress.svg',
    title: 'DRESS & FROCK',
    count: '(52)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/coat.svg',
    title: 'WINTER WEAR',
    count: '(5)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/glasses.svg',
    title: 'GLASSES & LENS',
    count: '(63)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/shorts.svg',
    title: 'SHORTS & JEANS',
    count: '(41)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/dress.svg',
    title: 'T-SHIRTS',
    count: '(32)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/jacket.svg',
    title: 'JACKET',
    count: '(24)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/watch.svg',
    title: 'WATCH',
    count: '(75)',
  },
  {
    icon: 'https://azureapis.blob.core.windows.net/share-account/assets/images/icons/hat.svg',
    title: 'HAT & CAPS',
    count: '(12)',
  },
];

export const BolgSwiper = [
  {
    pic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/blog-1.jpg',
    title: 'Fashion',
    info: 'Clothes Retail KPIs 2021 Guide for Clothes Executives.',
    date: 'By Mr Admin / Apr 06, 2022',
  },
  {
    pic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/blog-2.jpg',
    title: 'Clothes',
    info: 'Curbside fashion Trends: How to Win the Pickup Battle.',
    date: 'By Mr Robin / Jan 18, 2022',
  },
  {
    pic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/blog-3.jpg',
    title: 'Shoes',
    info: 'EBT vendors: Claim Your Share of SNAP Online Revenue.',
    date: 'By Mr Selsa / Feb 10, 2022',
  },
  {
    pic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/blog-4.jpg',
    title: 'Electronics',
    info: 'Curbside fashion Trends: How to Win the Pickup Battle.',
    date: 'By Mr Pawar / Mar 15, 2022',
  },
];

export const NewProducts = [
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/jacket-3.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/jacket-4.jpg',
    productName: 'JACKET',
    productInfo: 'Mens Winter Leathers Jackets',
    productPrice: '$48.00',
    taxPrice: '$25.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shirt-1.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shirt-2.jpg',
    productName: 'SHIRT',
    productInfo: 'Pure Garment Dyed Cotton Shirt',
    productPrice: '$45.00',
    taxPrice: '$26.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/jacket-5.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/jacket-6.jpg',
    productName: 'JACKET',
    productInfo: 'MEN Yarn Fleece Full-Zip Jacket',
    productPrice: '$58.00',
    taxPrice: '$25.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/clothes-3.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/clothes-4.jpg',
    productName: 'SKIRT',
    productInfo: 'Black Floral Wrap Midi Skirt',
    productPrice: '$58.00',
    taxPrice: '$55.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shoe-2.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shoe-2_1.jpg',
    productName: 'CASUAL',
    productInfo: "Casual Men's Brown Shoes",
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/watch-3.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/watch-4.jpg',
    productName: 'WATCHES',
    productInfo: 'Pocket Watch Leather Pouch',
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '15%',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/watch-1.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/watch-2.jpg',
    productName: 'WATCHES',
    productInfo: 'Smart Watche Vital Plus',
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/party-wear-1.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/party-wear-2.jpg',
    productName: 'PARTY WEAR',
    productInfo: 'Womens Party Wear Shoes',
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/jacket-1.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/jacket-2.jpg',
    productName: 'JACKET',
    productInfo: 'Mens Winter Leathers Jackets',
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/sports-2.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/sports-4.jpg',
    productName: 'SPORTS',
    productInfo: 'Trekking & Running Shoes - Black',
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '15%',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shoe-1.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shoe-1_1.jpg',
    productName: 'FORMAL',
    productInfo: "Men's Leather Formal Wear Shoes",
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
  {
    present: '',
    productPic: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shorts-1.jpg',
    productHover: 'https://azureapis.blob.core.windows.net/share-account/assets/images/products/shorts-2.jpg',
    productName: 'SHORTS',
    productInfo: 'Better Basics French Terry Sweatshorts',
    productPrice: '$48.00',
    taxPrice: '$75.00',
  },
];
