name: 04.deploy-adn

on:
  workflow_dispatch:
    inputs:
      confirmDeployment:
        description: 'Confirm Deployment'
        required: true
env:
  SERVER_IP: "20.39.193.105"
  SERVER_USER: "azureuser"
  IMAGE: adn
  DOCKER_HUB_USERNAME: warjamma

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            sudo docker pull $DOCKER_HUB_USERNAME/$IMAGE:latest
            sudo docker stop $IMAGE || true
            sudo docker rm $IMAGE || true
            sudo docker run -d -p 9000:3000 --name $IMAGE $DOCKER_HUB_USERNAME/$IMAGE:latest
            sudo docker image prune -f
          "